### ISSUE TITLE
Release notes are out of date on readthedocs

### ISSUE THREAD

**Issue by intgr** [jamielennox/requests-mock#168]
Hi! Thanks for your continued work on requests-mock.

I notice that release notes are available on GitHub (https://github.com/jamielennox/requests-mock/releases/tag/1.9.0) but are outdated on the readthedocs page: https://requests-mock.readthedocs.io/en/latest/release-notes.html

**Comment by jamielennox** [comment]
looks like readthedocs is trying to build with python2.7 and dulwich has upgraded in a python3 only way. I'll try and get this fixed.

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/reno/sphinxext.py", line 23, in <module>
    from dulwich import repo
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/dulwich/repo.py", line 51, in <module>
    from dulwich.object_store import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/dulwich/object_store.py", line 31, in <module>
    from dulwich.diff_tree import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/dulwich/diff_tree.py", line 32, in <module>
    from dulwich.objects import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/dulwich/objects.py", line 154
    def object_header(num_type: int, length: int) -> bytes:
                              ^
SyntaxError: invalid syntax

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/dulwich/diff_tree.py", line 32, in <module>
    from dulwich.objects import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/requests-mock/envs/1.9.3/lib/python2.7/site-packages/dulwich/objects.py", line 154
    def object_header(num_type: int, length: int) -> bytes:
                              ^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-VMOal7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by jamielennox** [comment]
That was a super easy fix, just switch to python3 in the readthedocs settings. Sorry it took so long.
